DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS item;
DROP TABLE IF EXISTS cart;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  admin INTEGER NOT NULL
);


CREATE TABLE orders (
    fnm TEXT NOT NULL,
    lnm TEXT NOT NULL,
    unm TEXT NOT NULL,
    eml TEXT NOT NULL,
    ad1 TEXT NOT NULL,
    ad2 TEXT NOT NULL,
    cnt TEXT NOT NULL,
    stt TEXT NOT NULL,
    zip TEXT NOT NULL,
    sad TEXT NOT NULL,
    pay TEXT NOT NULL,
);